# Habilita o AndroidX (necessário para o Jetpack Compose e Room)
android.useAndroidX=true

# Alocação de memória para compilação rápida no GitHub
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Permite compilação com a API 36
android.suppressUnsupportedCompileSdk=36

# Habilita compilação paralela
org.gradle.parallel=true
